### ISSUE TITLE
【性能】请问是否使用Ground Truth的触发词和事件类型？

### ISSUE THREAD

**Issue by kk19990709** [mayubo2333/PAIE#1]
请问您的对比实验中，其他的事件抽取模型（OneIE，EEQA，Text2Event等）是否使用Ground Truth的触发词和事件类型？如果没有会不会不太公平？

**Comment by mayubo2333** [comment]
我们使用了Ground Truth的触发词和事件类型。不使用Ground Truth的结果可见其他事件抽取的原论文结果。

**Comment by mayubo2333** [comment]
> 请问您的对比实验中，其他的事件抽取模型（OneIE，EEQA，Text2Event等）是否使用Ground Truth的触发词和事件类型？如果没有会不会不太公平？

Hi, here are some more words about it:

事件参数抽取的模型（无论是我们的模型还是baseline)都默认是用ground truth的触发词和事件类型。以EEQA为例：原论文中Table3汇报的结果53.3是不使用Ground Truth的结果，Table5汇报的结果65.4是使用Ground Truth的结果。我们在文中直接取了原作者汇报的结果：）

如果您没有其他问题，我将关闭这个issue。

**Comment by kk19990709** [comment]
十分感谢您详细的解答。我觉得这是一篇很好的工作，把提示学习引入了信息抽取领域。感谢你们的贡献。

**Comment by mayubo2333** [comment]
谢谢您对我们工作的关注和兴趣。
