### ISSUE TITLE
关于Head-C 指标

### ISSUE THREAD

**Issue by Lilice-r** [mayubo2333/PAIE#10]
您好，请问该指标只用判断 论元的head span正确就可以了吗？是否还要求角色也识别正确？
因为我看BartGen代码里似乎是head word span + role name

**Comment by mayubo2333** [comment]
您好，需要

> 您好，请问该指标只用判断 论元的head span正确就可以了吗？是否还要求角色也识别正确？ 因为我看BartGen代码里似乎是head word span + role name

您好，我们和BartGen的判断标准是相同的，参见metric.py#L105 （对每一个role中的argument分别判断）

**Comment by mayubo2333** [comment]
> 您好，请问该指标只用判断 论元的head span正确就可以了吗？是否还要求角色也识别正确？ 因为我看BartGen代码里似乎是head word span + role name

您好，我们和BartGen的判断标准是相同的，参见metric.py#L105 （对每一个role中的argument分别判断）

**Comment by Lilice-r** [comment]
> > 您好，请问该指标只用判断 论元的head span正确就可以了吗？是否还要求角色也识别正确？ 因为我看BartGen代码里似乎是head word span + role name
> 
> 您好，我们和BartGen的判断标准是相同的，参见metric.py#L105 （对每一个role中的argument分别判断）

晓得了~ 谢谢您的回复！
