### ISSUE TITLE
About result comparison

### ISSUE THREAD

**Issue by foxlf823** [mayubo2333/PAIE#11]
Hello author,

Thanks for sharing the code. I have one question when reading the paper w.r.t. the result comparison with the baseline BART-Gen. Some results in Table 2 of your paper have mismatches with the results in the paper of BART-Gen. For example, the Arg-I Arg-C Head-C numbers for WIKIEVENTS are 66.8 62.4 65.4, but I can't find exactly the same numbers in either Table 5 or 6 in the paper of BART-Gen. Are these results reproduced by yourself? If so,  it seems that they are very different from the numbers in the original paper.
no offense, but just confused about this issue. Did I miss some experimental details?

**Comment by mayubo2333** [comment]
> Hello author,
> 
> Thanks for sharing the code. I have one question when reading the paper w.r.t. the result comparison with the baseline BART-Gen. Some results in Table 2 of your paper have mismatches with the results in the paper of BART-Gen. For example, the Arg-I Arg-C Head-C numbers for WIKIEVENTS are 66.8 62.4 65.4, but I can't find exactly the same numbers in either Table 5 or 6 in the paper of BART-Gen. Are these results reproduced by yourself? If so, it seems that they are very different from the numbers in the original paper. no offense, but just confused about this issue. Did I miss some experimental details?

Hi, 
thanks for your interest on our work. The BART-Gen results of WIKIEVENTS is reproduced by ourselves and, from our understanding, are comparable with Table 5 in original paper. Please note that we adopt Arg-C (exact match required, more strictly) and Head-C, while the original paper adopt Head-C and Coref-C as evaluation metrics. We report similar Head-C score (65.4) compared with them (64.6).

**Comment by foxlf823** [comment]
Got it! Thank you
