### ISSUE TITLE
Question about argument-trigger distance experiment

### ISSUE THREAD

**Issue by hlee-top** [mayubo2333/PAIE#12]
Hello, thanks for the work you do!
I have some doubts about the trigger-argument distance experiment, can you provide me with more details of the implementation process?

**Comment by mayubo2333** [comment]
Hi, thanks for your interest. 
Could you provide a targeted explanation about your problem?

**Comment by hlee-top** [comment]
For trigger-argument distance experiment, my steps are as follows:
After training the model, the ground truth label and the predicted label are divided into 5 sets according to the distance between the trigger word and the argument, and then F1 is calculated in each set.
I found the overall F1 to be reasonable, but the F1 per set was slightly lower, so wanted to ask you if I was missing some steps, thanks for the reply.

**Comment by mayubo2333** [comment]
Yes, your steps are right.
According to our experiments, we find the F1-scores grouped by distances are highly unstable (especially the +2 and -2 settings), since the argument amount in these settings are too small (tens of, I remember?). Suggest you to train with other random seeds.

**Comment by hlee-top** [comment]
When dividing the distance sets of ground truth label and predicted label, should we use the ground truth label and predicted label for distance judgment, or use both ground truth label?

**Comment by mayubo2333** [comment]
Use ground truth label only.

**Comment by hlee-top** [comment]
thanks for your answer.
