### ISSUE TITLE
cuda device

### ISSUE THREAD

**Issue by simon-p-j-r** [mayubo2333/PAIE#13]
hello, 
how to chage the number of gpu?
It doesn't work when I add ''os.environ['CUDA_VISIBLE_DEVICES'] = "2"", and I didn't find where is the code that you set gpu.

**Comment by mayubo2333** [comment]
We run our code on service cluster with automatic GPU assignment and there is no code setting the GPU.

**Comment by simon-p-j-r** [comment]
thank you for your reply very much.
