### ISSUE TITLE
Question about sentence segmentation

### ISSUE THREAD

**Issue by hlee-top** [mayubo2333/PAIE#14]
Hello, I don't understand why W should be divided by 2 in line 208 of the code below. I found that this will cause the position of event_trigger to become a negative value, so I think W should not be divided by 2 in line 208. I hope to get your answer. Thanks！

https://github.com/mayubo2333/PAIE/blob/e0da77813bf52ab86ceae521073bd1867c66b6fe/processors/processor_base.py#L207-L217

**Comment by mayubo2333** [comment]
Hi, this processor is designed for RAMS datasets. For longer sentences, please refer to 
https://github.com/mayubo2333/PAIE/blob/e0da77813bf52ab86ceae521073bd1867c66b6fe/processors/processor_base.py#L271-L289

**Comment by hlee-top** [comment]
Is it also correct to use only W as the judgment condition, not W divided by 2?

**Comment by mayubo2333** [comment]
I don't carefully check, but I think it's also OK.

**Comment by hlee-top** [comment]
thank you for your reply very much.
