### ISSUE TITLE
Question about evaluation on RAMS dataset

### ISSUE THREAD

**Issue by xinsu626** [mayubo2333/PAIE#2]
Hello, nice work, and thanks for sharing the code!

I have a question about the RAMS dataset. It looks like some arguments get dropped because of the window size. Were the dropped arguments included in the final test set? Thank you very much!

**Comment by mayubo2333** [comment]
> Hello, nice work, and thanks for sharing the code!
> 
> I have a question about the RAMS dataset. It looks like some arguments get dropped because of the window size. Were the dropped arguments included in the final test set? Thank you very much!

Hi，thanks for your interest about our work.

We count the arguments out of the window and consider it during evaluation. Actually, there is only 1-2 argument out of the window in RAMS dev/test dataset.

**Comment by xinsu626** [comment]
> > Hello, nice work, and thanks for sharing the code!
> > I have a question about the RAMS dataset. It looks like some arguments get dropped because of the window size. Were the dropped arguments included in the final test set? Thank you very much!
> 
> Hi，thanks for your interest about our work.
> 
> We count the arguments out of the window and consider it during evaluation. Actually, there is only 1-2 argument out of the window in RAMS dev/test dataset.

Got it. Thank you for your help!
