### ISSUE TITLE
prompt full data 

### ISSUE THREAD

**Issue by xxllp** [mayubo2333/PAIE#4]
why the prompt template have "prompt start"  and " end" ,which is not show in the paper  . Is it get an  better result ?

**Comment by mayubo2333** [comment]
we found 

> why the prompt template have "prompt start" and " end" ,which is not show in the paper . Is it get an better result ?

we found that adding them could get slightly better improvement. But dropping them is also OK (No significant influence).

**Comment by xxllp** [comment]
thx, I get it  ~~
and   can I  use the code on an chinese dataset  ，or   some code needs to be modified

**Comment by mayubo2333** [comment]
> thx, I get it ~~ and can I use the code on an chinese dataset ，or some code needs to be modified

Thanks for your interest. I don't make experiment on Chinese dataset, but I think the modification is mainly in processor/prompt module and should not be heavy. You could have a try :)
