### ISSUE TITLE
ACE05数据集

### ISSUE THREAD

**Issue by cjj-sunshine** [mayubo2333/PAIE#5]
ACE05数据集在LDC网站上好像不是免费下载的，请问您是否可以提供一下这个数据集呢？希望能尽快得到您的回复！

**Comment by mayubo2333** [comment]
你好，ACL2005不是公开数据集，我无权免费提供。

**Comment by mayubo2333** [comment]
> ACE05数据集在LDC网站上好像不是免费下载的，请问您是否可以提供一下这个数据集呢？希望能尽快得到您的回复！

你好，ACL2005不是公开数据集，我无权免费提供。

**Comment by cjj-sunshine** [comment]
> > ACE05数据集在LDC网站上好像不是免费下载的，请问您是否可以提供一下这个数据集呢？希望能尽快得到您的回复！
> 
> 你好，ACL2005不是公开数据集，我无权免费提供。

好的，谢谢
