### ISSUE TITLE
How to add a new dataset

### ISSUE THREAD

**Issue by h-peng17** [mayubo2333/PAIE#9]
Thanks for your code! I have some questions about how to add a new dataset. I think there are 3 steps to add a new dataset:
1. Place the data in the `./data` folder.
2. Add data reading code in `DSET_processor` class in `processor_base.py` file. And modify some details such as arg parser and `build_processor`.
3. Add the description file in `./data/dset_meta` folder and the prompt file in `./data/prompts` folder. 
Then I can run the code to train/infer on my own dataset. Are there any misunderstandings? Thank you!

**Comment by mayubo2333** [comment]
Hi, thanks for your interest!
I'm sorry the code was written long ago so I couldn't remember every details. But I think your understanding is right.
Feel free to ask me later if you encounter new problems in your own dataset.
